spring.application.name=ecommerce-backend
# ===============================
# = DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:oracle:thin:@oracle.scs.ryerson.ca:1521:orcl
spring.profiles.active=local
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

#for logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# AWS S3 config
aws.s3.bucket-name=3d-model-store
aws.s3.region=us-east-2

storage.mode=s3
